[module]
  [module.hugoVersion]
    min = "v0.121.2"

  [[module.mounts]]
    source = "select.html"
    target = "layouts/partials/components/select.html"

  [[module.mounts]]
    source = "shortcode.html"
    target = "layouts/shortcodes/components/select.html"
