[module]
  [module.hugoVersion]
    min = "0.128.0"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "tailwind.html"
    target = "layouts/partials/tailwind.html"
