[module]
  [[module.imports]]
    path = "github.com/hebs-web-design/hugo-modules/alpinejs/v3"

  [[module.mounts]]
    source = "search.js"
    target = "assets/js/alpinejs/search.js"

  [[module.mounts]]
    source = "partial.html"
    target = "layouts/partials/search.html" 
