[module]
  [module.hugoVersion]
    min = "v0.121.2"

  [[module.mounts]]
    source = "input.html"
    target = "layouts/partials/components/input.html"

  [[module.mounts]]
    source = "shortcode.html"
    target = "layouts/shortcodes/components/input.html"
