[module]
  [[module.imports]]
    path = "github.com/caressofsteel/hugo-story"

  [[module.imports.mounts]]
    source = "assets"
    target = "assets"

  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.imports.mounts]]
    source = "static/css"
    target = "static/css"
  
  [[module.imports.mounts]]
    source = "static/js"
    target = "static/js"

  [[module.imports.mounts]]
    source = "static/webfonts"
    target = "static/webfonts"
