[module]
  [module.hugoVersion]
    min = "v0.121.2"

  [[module.imports]]
    path = "github.com/hebs-web-design/hugo-modules/alpinejs/toggler"
  
  [[module.imports]]
    path = "github.com/hebs-web-design/hugo-modules/picture"

  [[module.imports]]
    path = "github.com/hebs-web-design/hugo-modules/tailwindcss/v3"

  [[module.mounts]]
    source = "partial.html"
    target = "layouts/partials/gallery.html"

  [[module.mounts]]
    source = "shortcode.html"
    target = "layouts/shortcodes/gallery.html"
