[module]
  [module.hugoVersion]
    min = "v0.121.2"

  [[module.imports]]
    path = "github.com/hebs-web-design/hugo-modules/utilities"

  [[module.mounts]]
    source = "partial/picture.html"
    target = "layouts/partials/picture.html"

  [[module.mounts]]
    source = "shortcode/picture.html"
    target = "layouts/shortcodes/picture.html"