[module]

[[module.imports]]
  path = "github.com/hebs-web-design/hugo-modules/alpinejs/toggler"

[[module.imports]]
  path = "github.com/hebs-web-design/hugo-modules/alpinejs/search"

[[module.mounts]]
  source = "partial.html"
  target = "layouts/partials/navbar.html"