[module]

[[module.mounts]]
source = "layouts/directory"
target = "layouts/directory"

[[module.mounts]]
source = "layouts/partials"
target = "layouts/partials/directory"

[[module.mounts]]
source = "layouts/shortcodes/directory.html"
target = "layouts/shortcodes/directory.html"

[[module.mounts]]
source = "static/img"
target = "static/directory/img"

[[module.mounts]]
source = "static/icons"
target = "static/directory/icons"

[[module.mounts]]
source = "assets/js"
target = "assets/js/directory"

[[module.mounts]]
source = "assets/css"
target = "assets/css/directory"

[[module.mounts]]
source = "assets/static"
target = "assets/static/directory"

[[module.mounts]]
source = "node_modules/leaflet/dist/leaflet.css"
target = "assets/vendor/leaflet.css"

[[module.mounts]]
source = "node_modules/leaflet/dist/images"
target = "static/vendor/leaflet/images"