[module]

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static/img"
target = "static/img"

[[module.mounts]]
source = "assets/js/data.js"
target = "assets/js/data.js"

[[module.mounts]]
source = "assets/js/template.js"
target = "assets/js/template.js"

[[module.mounts]]
source = "assets/css/main.css"
target = "assets/css/main.css"