[module]

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "static/img"
target = "static/img"

[[module.mounts]]
source = "assets/js"
target = "assets/js"

[[module.mounts]]
source = "assets/css"
target = "assets/css"